In [66]:
import pandas as pd

In [67]:
df = pd.read_csv("nba_games.csv", index_col=0)

In [68]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,22.8,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True
1,240.0,240.0,36.0,100.0,0.360,7.0,31.0,0.226,16.0,19.0,...,50.0,32.6,152.0,111.0,ATL,98,0,2016,2015-12-09,False
2,240.0,240.0,37.0,85.0,0.435,8.0,19.0,0.421,17.0,23.0,...,20.0,30.9,148.0,116.0,SAS,107,1,2018,2017-10-18,False
3,240.0,240.0,41.0,89.0,0.461,8.0,21.0,0.381,17.0,19.0,...,28.6,30.9,138.0,118.0,MIN,99,0,2018,2017-10-18,True
4,240.0,240.0,35.0,83.0,0.422,9.0,24.0,0.375,12.0,18.0,...,33.3,30.9,171.0,105.0,MIN,107,1,2017,2017-03-08,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12967,240.0,240.0,35.0,81.0,0.432,11.0,26.0,0.423,27.0,36.0,...,34.2,33.7,160.0,118.0,OKC,92,0,2019,2018-10-19,True
12968,240.0,240.0,37.0,74.0,0.500,13.0,25.0,0.520,26.0,37.0,...,25.0,30.0,139.0,129.0,ORL,108,1,2017,2016-12-14,True
12969,240.0,240.0,42.0,89.0,0.472,14.0,33.0,0.424,10.0,20.0,...,25.6,29.9,175.0,126.0,LAC,113,0,2017,2016-12-14,False
12970,240.0,240.0,41.0,85.0,0.482,9.0,26.0,0.346,26.0,30.0,...,27.7,27.1,150.0,126.0,MIA,106,1,2020,2020-09-19,True
12971,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,34.0,...,51.5,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False

In [69]:
df = df.sort_values("date")

In [70]:
df = df.reset_index(drop=True)

In [71]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [72]:
def add_target(team):
    team["target"] = team["won"].shift(-1)
    return team

df = df.groupby("team", group_keys=False).apply(add_target)

In [73]:
df[df["team"] == "WAS"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
31,240.0,33.0,84.0,0.393,7.0,28.0,0.250,15.0,25.0,0.600,...,25.2,134.0,98.0,ORL,87,1,2016,2015-10-28,True,True
40,240.0,35.0,68.0,0.515,12.0,21.0,0.571,36.0,44.0,0.818,...,32.4,138.0,122.0,MIL,113,1,2016,2015-10-30,True,False
69,240.0,38.0,90.0,0.422,6.0,22.0,0.273,28.0,33.0,0.848,...,28.7,153.0,108.0,NYK,117,0,2016,2015-10-31,False,True
126,240.0,42.0,87.0,0.483,8.0,23.0,0.348,10.0,14.0,0.714,...,30.0,160.0,109.0,SAS,99,0,2016,2015-11-04,True,False
158,240.0,36.0,88.0,0.409,8.0,25.0,0.320,18.0,23.0,0.783,...,41.6,146.0,103.0,BOS,118,1,2016,2015-11-06,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12806,240.0,41.0,81.0,0.506,11.0,31.0,0.355,18.0,25.0,0.720,...,35.2,175.0,112.0,MEM,125,0,2021,2021-03-02,False,True
12841,240.0,40.0,88.0,0.455,9.0,23.0,0.391,30.0,42.0,0.714,...,30.6,190.0,123.0,LAC,117,0,2021,2021-03-04,True,False
12851,240.0,38.0,95.0,0.400,11.0,36.0,0.306,25.0,27.0,0.926,...,30.4,166.0,108.0,MEM,127,1,2021,2021-03-10,False,False
12879,240.0,40.0,82.0,0.488,8.0,24.0,0.333,13.0,22.0,0.591,...,34.4,166.0,109.0,PHI,127,0,2021,2021-03-12,False,False
12894,240.0,39.0,79.0,0.494,8.0,20.0,0.400,26.0,33.0,0.788,...,30.9,181.0,121.0,PHI,129,1,2021,2021-06-02,False,NaN

In [74]:
df["target"][pd.isnull(df["target"])] = 2
df["target"] = df["target"].astype(int, errors="ignore")

/var/folders/dn/_lvwvnb56mq5h1q8qdv2hcdr0000gn/T/ipykernel_1038/2793819745.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [75]:
df["won"].value_counts()

False    6486
True     6486
Name: won, dtype: int64

In [76]:
df["target"].value_counts()

1    6472
0    6470
2      30
Name: target, dtype: int64

In [77]:
nulls = pd.isnull(df).sum()

In [78]:
nulls = nulls[nulls > 0]

In [79]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [80]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=142)

In [81]:
df = df[valid_columns].copy()

In [82]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
1,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
2,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,1
3,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True,1
4,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12967,240.0,46.0,84.0,0.548,10.0,30.0,0.333,14.0,15.0,0.933,...,31.1,123.0,123.0,PHO,102,1,2021,2021-06-28,True,0
12968,240.0,33.0,84.0,0.393,8.0,39.0,0.205,14.0,19.0,0.737,...,48.0,212.0,108.0,ATL,110,1,2021,2021-06-29,False,2
12969,240.0,43.0,85.0,0.506,13.0,38.0,0.342,11.0,13.0,0.846,...,43.5,123.0,126.0,MIL,88,0,2021,2021-06-29,True,2
12970,240.0,33.0,79.0,0.418,12.0,39.0,0.308,25.0,32.0,0.781,...,44.1,200.0,119.0,PHO,130,0,2021,2021-06-30,False,2
12971,240.0,53.0,94.0,0.564,17.0,31.0,0.548,7.0,11.0,0.636,...,39.1,145.0,145.0,LAC,103,1,2021,2021-06-30,True,2

In [83]:
from sklearn.linear_model import RidgeClassifier
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.model_selection import TimeSeriesSplit

rr = RidgeClassifier(alpha=1)

split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, 
                                n_features_to_select=20, 
                                direction="forward",
                                cv=split
                               )

In [84]:
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [85]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [86]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.452381,0.500000,0.325301,0.333333,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.158301,0.345972,0.325301,CHI,0.317308,1.0,2016,2015-10-27,False,1
1,0.0,0.428571,0.397059,0.375904,0.259259,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.086229,0.232227,0.337349,CLE,0.298077,0.0,2016,2015-10-27,True,1
2,0.0,0.523810,0.529412,0.380723,0.333333,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.213642,0.530806,0.518072,NOP,0.298077,0.0,2016,2015-10-27,True,1
3,0.0,0.428571,0.529412,0.279518,0.444444,0.378788,0.491686,0.441860,0.396825,0.730455,...,0.148005,0.800948,0.530120,ATL,0.288462,1.0,2016,2015-10-27,True,1
4,0.0,0.380952,0.338235,0.368675,0.222222,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.275418,0.554502,0.325301,GSW,0.451923,1.0,2016,2015-10-27,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12967,0.0,0.642857,0.352941,0.672289,0.370370,0.393939,0.395487,0.302326,0.222222,0.921820,...,0.113256,0.161137,0.554217,PHO,0.365385,1.0,2021,2021-06-28,True,0
12968,0.0,0.333333,0.352941,0.298795,0.296296,0.530303,0.243468,0.302326,0.285714,0.693116,...,0.330759,0.582938,0.373494,ATL,0.442308,1.0,2021,2021-06-29,False,2
12969,0.0,0.571429,0.367647,0.571084,0.481481,0.515152,0.406176,0.232558,0.190476,0.820303,...,0.272844,0.161137,0.590361,MIL,0.230769,0.0,2021,2021-06-29,True,2
12970,0.0,0.333333,0.279412,0.359036,0.444444,0.530303,0.365796,0.558140,0.492063,0.744457,...,0.280566,0.526066,0.506024,PHO,0.634615,0.0,2021,2021-06-30,False,2
12971,0.0,0.809524,0.500000,0.710843,0.629630,0.409091,0.650831,0.139535,0.158730,0.575263,...,0.216216,0.265403,0.819277,LAC,0.375000,1.0,2021,2021-06-30,True,2

In [87]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=20)

In [88]:
predictors = list(selected_columns[sfs.get_support()])

In [89]:
predictors

['ft%',
 'drb%',
 'usg%',
 'pts_max',
 '+/-_max',
 'drb%_max',
 'trb%_max',
 'tov%_max',
 'pts_opp',
 'orb%_opp',
 'stl%_opp',
 'usg%_opp',
 'fg_max_opp',
 '3p_max_opp',
 'ft%_max_opp',
 'pts_max_opp',
 'stl%_max_opp',
 'tov%_max_opp',
 'usg%_max_opp',
 'total_opp']

In [90]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []
    
    seasons = sorted(data["season"].unique())
    
    for i in range(start, len(seasons), step):
        season = seasons[i]
        train = data[data["season"] < season]
        test = data[data["season"] == season]
        
        model.fit(train[predictors], train["target"])
        
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "prediction"]
        
        all_predictions.append(combined)
        
    return pd.concat(all_predictions)

In [91]:
predictions = backtest(df, rr, predictors)

In [92]:
predictions

       actual  prediction
5250        1           1
5251        0           0
5252        1           0
5253        1           1
5254        0           1
...       ...         ...
12967       0           1
12968       2           0
12969       2           1
12970       2           0
12971       2           1

[7722 rows x 2 columns]

In [93]:
from sklearn.metrics import accuracy_score

accuracy_score(predictions["actual"], predictions["prediction"])

0.541958041958042

In [94]:
df.groupby(["home"]).apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

home
0.0    0.419519
1.0    0.580481
dtype: float64

In [95]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.452381,0.500000,0.325301,0.333333,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.158301,0.345972,0.325301,CHI,0.317308,1.0,2016,2015-10-27,False,1
1,0.0,0.428571,0.397059,0.375904,0.259259,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.086229,0.232227,0.337349,CLE,0.298077,0.0,2016,2015-10-27,True,1
2,0.0,0.523810,0.529412,0.380723,0.333333,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.213642,0.530806,0.518072,NOP,0.298077,0.0,2016,2015-10-27,True,1
3,0.0,0.428571,0.529412,0.279518,0.444444,0.378788,0.491686,0.441860,0.396825,0.730455,...,0.148005,0.800948,0.530120,ATL,0.288462,1.0,2016,2015-10-27,True,1
4,0.0,0.380952,0.338235,0.368675,0.222222,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.275418,0.554502,0.325301,GSW,0.451923,1.0,2016,2015-10-27,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12967,0.0,0.642857,0.352941,0.672289,0.370370,0.393939,0.395487,0.302326,0.222222,0.921820,...,0.113256,0.161137,0.554217,PHO,0.365385,1.0,2021,2021-06-28,True,0
12968,0.0,0.333333,0.352941,0.298795,0.296296,0.530303,0.243468,0.302326,0.285714,0.693116,...,0.330759,0.582938,0.373494,ATL,0.442308,1.0,2021,2021-06-29,False,2
12969,0.0,0.571429,0.367647,0.571084,0.481481,0.515152,0.406176,0.232558,0.190476,0.820303,...,0.272844,0.161137,0.590361,MIL,0.230769,0.0,2021,2021-06-29,True,2
12970,0.0,0.333333,0.279412,0.359036,0.444444,0.530303,0.365796,0.558140,0.492063,0.744457,...,0.280566,0.526066,0.506024,PHO,0.634615,0.0,2021,2021-06-30,False,2
12971,0.0,0.809524,0.500000,0.710843,0.629630,0.409091,0.650831,0.139535,0.158730,0.575263,...,0.216216,0.265403,0.819277,LAC,0.375000,1.0,2021,2021-06-30,True,2

In [96]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

def find_team_averages(team):
    rolling = team.rolling(7).mean()
    return rolling

df_rolling = df_rolling.groupby(["team", "season"], group_keys=False).apply(find_team_averages)

/var/folders/dn/_lvwvnb56mq5h1q8qdv2hcdr0000gn/T/ipykernel_1038/2232342384.py:4: FutureWarning: Dropping of nuisance columns in rolling operations is deprecated; in a future version this will raise TypeError. Select only valid columns before calling the operation. Dropped columns were Index(['team'], dtype='object')
  rolling = team.rolling(7).mean()

In [97]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,season
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12967,0.000000,0.482993,0.340336,0.490189,0.507937,0.491342,0.435697,0.385382,0.333333,0.786298,...,0.045143,0.046857,0.370788,0.178525,0.504401,0.588640,0.390110,0.571429,0.571429,2021.0
12968,0.035714,0.554422,0.447479,0.477453,0.407407,0.471861,0.374449,0.299003,0.292517,0.661944,...,0.068714,0.213857,0.261625,0.245266,0.539607,0.569707,0.391484,0.571429,0.571429,2021.0
12969,0.000000,0.486395,0.386555,0.451979,0.375661,0.430736,0.369019,0.332226,0.315193,0.697616,...,0.076857,0.062571,0.299893,0.196543,0.301286,0.473322,0.407967,0.571429,0.571429,2021.0
12970,0.000000,0.455782,0.338235,0.457487,0.486772,0.489177,0.420088,0.398671,0.349206,0.776463,...,0.040000,0.051286,0.294557,0.205552,0.535545,0.561102,0.416209,0.428571,0.428571,2021.0
12971,0.000000,0.537415,0.399160,0.499484,0.354497,0.348485,0.408551,0.335548,0.263039,0.848308,...,0.057286,0.048429,0.293185,0.407428,0.407583,0.545611,0.401099,0.571429,0.714286,2021.0

In [98]:
rolling_cols = [f"{col}_7" for col in df_rolling.columns]
df_rolling.columns = rolling_cols
df = pd.concat([df, df_rolling], axis=1)

In [99]:
df = df.dropna()

In [100]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp_7,blk%_max_opp_7,tov%_max_opp_7,usg%_max_opp_7,ortg_max_opp_7,drtg_max_opp_7,total_opp_7,home_opp_7,won_7,season_7
162,0.0,0.523810,0.250000,0.633735,0.333333,0.257576,0.509501,0.674419,0.539683,0.833139,...,0.059714,0.079571,0.399604,0.100386,0.399458,0.445783,0.328297,0.571429,0.857143,2016.0
170,0.0,0.452381,0.470588,0.346988,0.296296,0.530303,0.243468,0.418605,0.333333,0.841307,...,0.072143,0.085857,0.304620,0.191028,0.409614,0.538726,0.321429,0.428571,1.000000,2016.0
172,0.0,0.476190,0.338235,0.484337,0.222222,0.136364,0.548694,0.465116,0.365079,0.854142,...,0.074000,0.065143,0.283122,0.137893,0.335139,0.418244,0.368132,0.571429,0.428571,2016.0
173,0.0,0.452381,0.382353,0.416867,0.259259,0.393939,0.276722,0.581395,0.444444,0.879813,...,0.068143,0.093429,0.539564,0.127781,0.376439,0.437177,0.428571,0.428571,0.571429,2016.0
174,0.0,0.452381,0.397059,0.404819,0.222222,0.227273,0.375297,0.255814,0.238095,0.708285,...,0.062429,0.118429,0.453575,0.152418,0.446175,0.428571,0.454670,0.285714,0.142857,2016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12967,0.0,0.642857,0.352941,0.672289,0.370370,0.393939,0.395487,0.302326,0.222222,0.921820,...,0.045143,0.046857,0.370788,0.178525,0.504401,0.588640,0.390110,0.571429,0.571429,2021.0
12968,0.0,0.333333,0.352941,0.298795,0.296296,0.530303,0.243468,0.302326,0.285714,0.693116,...,0.068714,0.213857,0.261625,0.245266,0.539607,0.569707,0.391484,0.571429,0.571429,2021.0
12969,0.0,0.571429,0.367647,0.571084,0.481481,0.515152,0.406176,0.232558,0.190476,0.820303,...,0.076857,0.062571,0.299893,0.196543,0.301286,0.473322,0.407967,0.571429,0.571429,2021.0
12970,0.0,0.333333,0.279412,0.359036,0.444444,0.530303,0.365796,0.558140,0.492063,0.744457,...,0.040000,0.051286,0.294557,0.205552,0.535545,0.561102,0.416209,0.428571,0.428571,2021.0
12971,0.0,0.809524,0.500000,0.710843,0.629630,0.409091,0.650831,0.139535,0.158730,0.575263,...,0.057286,0.048429,0.293185,0.407428,0.407583,0.545611,0.401099,0.571429,0.714286,2021.0

In [101]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df, col_name):
    return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))

df["home_next"] = add_col(df, "home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

In [102]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp_7,ortg_max_opp_7,drtg_max_opp_7,total_opp_7,home_opp_7,won_7,season_7,home_next,team_opp_next,date_next
162,0.0,0.523810,0.250000,0.633735,0.333333,0.257576,0.509501,0.674419,0.539683,0.833139,...,0.100386,0.399458,0.445783,0.328297,0.571429,0.857143,2016.0,1.0,WAS,2015-11-07
170,0.0,0.452381,0.470588,0.346988,0.296296,0.530303,0.243468,0.418605,0.333333,0.841307,...,0.191028,0.409614,0.538726,0.321429,0.428571,1.000000,2016.0,1.0,DET,2015-11-09
172,0.0,0.476190,0.338235,0.484337,0.222222,0.136364,0.548694,0.465116,0.365079,0.854142,...,0.137893,0.335139,0.418244,0.368132,0.571429,0.428571,2016.0,0.0,IND,2015-11-09
173,0.0,0.452381,0.382353,0.416867,0.259259,0.393939,0.276722,0.581395,0.444444,0.879813,...,0.127781,0.376439,0.437177,0.428571,0.428571,0.571429,2016.0,1.0,BRK,2015-11-11
174,0.0,0.452381,0.397059,0.404819,0.222222,0.227273,0.375297,0.255814,0.238095,0.708285,...,0.152418,0.446175,0.428571,0.454670,0.285714,0.142857,2016.0,1.0,SAS,2015-11-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12967,0.0,0.642857,0.352941,0.672289,0.370370,0.393939,0.395487,0.302326,0.222222,0.921820,...,0.178525,0.504401,0.588640,0.390110,0.571429,0.571429,2021.0,1.0,PHO,2021-06-30
12968,0.0,0.333333,0.352941,0.298795,0.296296,0.530303,0.243468,0.302326,0.285714,0.693116,...,0.245266,0.539607,0.569707,0.391484,0.571429,0.571429,2021.0,NaN,None,None
12969,0.0,0.571429,0.367647,0.571084,0.481481,0.515152,0.406176,0.232558,0.190476,0.820303,...,0.196543,0.301286,0.473322,0.407967,0.571429,0.571429,2021.0,NaN,None,None
12970,0.0,0.333333,0.279412,0.359036,0.444444,0.530303,0.365796,0.558140,0.492063,0.744457,...,0.205552,0.535545,0.561102,0.416209,0.428571,0.428571,2021.0,NaN,None,None
12971,0.0,0.809524,0.500000,0.710843,0.629630,0.409091,0.650831,0.139535,0.158730,0.575263,...,0.407428,0.407583,0.545611,0.401099,0.571429,0.714286,2021.0,NaN,None,None

In [103]:
full = df.merge(df[rolling_cols + ["team_opp_next", "date_next", "team"]], left_on=["team", "date_next"], right_on=["team_opp_next", "date_next"])

In [104]:
full

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp_7_y,usg%_max_opp_7_y,ortg_max_opp_7_y,drtg_max_opp_7_y,total_opp_7_y,home_opp_7_y,won_7_y,season_7_y,team_opp_next_y,team_y
0,0.0,0.476190,0.338235,0.484337,0.222222,0.136364,0.548694,0.465116,0.365079,0.854142,...,0.573258,0.160507,0.297901,0.383821,0.322802,0.428571,0.428571,2016.0,ORL,IND
1,0.0,0.452381,0.382353,0.416867,0.259259,0.393939,0.276722,0.581395,0.444444,0.879813,...,0.491843,0.228351,0.459716,0.337349,0.373626,0.571429,0.000000,2016.0,HOU,BRK
2,0.0,0.357143,0.323529,0.351807,0.111111,0.075758,0.395487,0.325581,0.285714,0.753792,...,0.539564,0.127781,0.376439,0.437177,0.428571,0.428571,0.571429,2016.0,BRK,HOU
3,0.0,0.333333,0.352941,0.298795,0.333333,0.348485,0.395487,0.534884,0.444444,0.799300,...,0.392438,0.312006,0.225457,0.435456,0.299451,0.714286,0.714286,2016.0,NYK,TOR
4,0.0,0.214286,0.161765,0.301205,0.111111,0.227273,0.187648,0.372093,0.333333,0.735123,...,0.453270,0.132561,0.354773,0.450947,0.350275,0.428571,0.428571,2016.0,TOR,NYK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11849,0.0,0.190476,0.338235,0.134940,0.185185,0.409091,0.191211,0.465116,0.492063,0.598600,...,0.497484,0.341239,0.587678,0.549053,0.375000,0.571429,0.857143,2021.0,LAC,PHO
11850,0.0,0.476190,0.352941,0.469880,0.555556,0.500000,0.480998,0.186047,0.238095,0.490082,...,0.337856,0.230189,0.494922,0.573150,0.372253,0.428571,0.714286,2021.0,ATL,MIL
11851,0.0,0.619048,0.411765,0.583133,0.407407,0.378788,0.450119,0.255814,0.317460,0.499417,...,0.275499,0.179629,0.421124,0.452668,0.424451,0.571429,0.571429,2021.0,MIL,ATL
11852,0.0,0.452381,0.352941,0.440964,0.333333,0.333333,0.410926,0.372093,0.301587,0.824971,...,0.370788,0.178525,0.504401,0.588640,0.390110,0.571429,0.571429,2021.0,PHO,LAC
11853,0.0,0.642857,0.352941,0.672289,0.370370,0.393939,0.395487,0.302326,0.222222,0.921820,...,0.383138,0.402280,0.512525,0.512909,0.399725,0.571429,0.714286,2021.0,LAC,PHO

In [105]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

      team_x team_opp_next_x team_y team_opp_next_y   date_next
0        ORL             IND    IND             ORL  2015-11-09
1        HOU             BRK    BRK             HOU  2015-11-11
2        BRK             HOU    HOU             BRK  2015-11-11
3        NYK             TOR    TOR             NYK  2015-11-10
4        TOR             NYK    NYK             TOR  2015-11-10
...      ...             ...    ...             ...         ...
11849    LAC             PHO    PHO             LAC  2021-06-28
11850    ATL             MIL    MIL             ATL  2021-06-29
11851    MIL             ATL    ATL             MIL  2021-06-29
11852    PHO             LAC    LAC             PHO  2021-06-30
11853    LAC             PHO    PHO             LAC  2021-06-30

[11854 rows x 5 columns]

In [106]:
removed_columns = list(full.columns[full.dtypes == "object"]) + removed_columns

In [107]:
removed_columns

['team_x',
 'team_opp',
 'date',
 'team_opp_next_x',
 'date_next',
 'team_opp_next_y',
 'team_y',
 'season',
 'date',
 'won',
 'target',
 'team',
 'team_opp']

In [108]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]
sfs.fit(full[selected_columns], full["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=20)

In [109]:
predictors = list(selected_columns[sfs.get_support()])

In [110]:
predictors

['usg%',
 'tov_max',
 'ft%_opp',
 'usg%_opp',
 'drb_max_opp',
 'trb%_7_x',
 'usg%_7_x',
 'pts_max_7_x',
 'pf_opp_7_x',
 'trb%_opp_7_x',
 'usg%_opp_7_x',
 'fg%_max_opp_7_x',
 'blk_max_opp_7_x',
 '+/-_max_opp_7_x',
 'home_next',
 'usg%_7_y',
 'pts_max_7_y',
 'fg_opp_7_y',
 'pf_opp_7_y',
 '+/-_max_opp_7_y']

In [111]:
predictions = backtest(full, rr, predictors)

In [112]:
accuracy_score(predictions["actual"], predictions["prediction"])

0.634024303073624